"""empty message

Revision ID: 06de3e2f641c
Revises: 
Create Date: 2025-04-08 05:07:01.284034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06de3e2f641c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_user_role')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ab_user_role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='ab_user_role_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ab_user_role_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ab_user_role_pkey'),
    sa.UniqueConstraint('user_id', 'role_id', name='ab_user_role_user_id_role_id_key')
    )
    # ### end Alembic commands ###
